name: Deploy

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Run Tests
        run: |
          JWT_PRIVATE_KEY=ABC yarn test

      - name: Build
        run: |
          yarn build

      - name: Copy files
        run: |
          rm dist/package.json
          cp package.json dist/package.json

      - name: Setup Package Manager
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"

      - name: Install the most recent version of NPM
        # This is done so the "set-script" command can be used
        run: |
          npm install -g npm@latest

      - name: Remove "prepare" and "build" script
        # This script must be removed because it uses
        # a devDependency and they doesn't exist in this context
        run: |
          cd ./dist
          npm set-script prepare ""
          npm set-script build ""
          cd ..

      - name: Create Procfile
        run: |
          echo "web: npm start" > dist/Procfile

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: release # The branch the action should deploy to.
          folder: dist # The folder the action should deploy

